# Generated by Django 5.1 on 2024-08-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistaPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='descripcion',
            new_name='descripcionTema',
        ),
        migrations.RenameField(
            model_name='tema',
            old_name='nombre',
            new_name='nombreTema',
        ),
    ]
