# Generated by Django 5.1 on 2024-08-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaPrincipal', '0002_rename_descripcion_tema_descripciontema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloArticulo', models.CharField(blank=True, max_length=128, null=True)),
                ('contenidoArticulo', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tema',
            name='nombreTema',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
