# Generated by Django 5.1 on 2024-08-20 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaPrincipal', '0003_articulo_alter_tema_nombretema'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='temaSeleccionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vistaPrincipal.tema'),
        ),
    ]
