# Generated by Django 5.1 on 2024-08-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaPrincipal', '0004_articulo_temaseleccionado'),
    ]

    operations = [
        migrations.CreateModel(
            name='busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoBusqueda', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
