# Generated by Django 5.1 on 2024-08-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaPrincipal', '0005_busqueda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda',
            name='textoBusqueda',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
